### ISSUE TITLE
Connecting author

### ISSUE THREAD

**Issue by kevinho** [rjl493456442/leveldb-handbook#19]
Thanks u for sharing, I am changbinhe@huobi blockchain team, could we connect via wechat? Mine is freeface

**Comment by marbar3778** [comment]
Hey, Im marko the cosmos-sdk lead. We would love to pick your brain on db related things. Would love to chat. Could you reach out via marko@interchain.io?

**Comment by rjl493456442** [comment]
@marbar3778 Feel free to open tickets for any database relevant stuff and I am happy to answer.
